apiVersion: v1
kind: Service
metadata:
  labels:
    service: concord3
  name: concord3
spec:
  ports:
    - name: "5458"
      port: 5458
      targetPort: 5458
    - name: "50051"
      port: 50051
      targetPort: 50051
    - name: "3501"
      port: 3501
      targetPort: 3501
  selector:
    service: concord3
status:
  loadBalancer: {}