apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: concord3
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "pods/log", "deployments", "configmaps", "secrets"]
  verbs: ["create", "get", "watch", "list", "update", "delete"]