apiVersion: v1
kind: Service
metadata:
  labels:
    service: clientservice1
  name: clientservice1
spec:
  ports:
    - name: "50505"
      port: 50505
      targetPort: 50505
  selector:
    service: clientservice1
status:
  loadBalancer: {}