apiVersion: v1
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: erc20test
    spec:
      template:
        metadata:
          labels:
            service: erc20test
        spec:
          containers:
            - name: erc20test
              image: python:3
              command: [ "/bin/sh", "-c", "bash ; pip3 install urllib3 web3 pytest pysha3 ; cd /tests ; python3 -m pytest --log-cli-level=DEBUG eth_erc20.py ; " ]
              volumeMounts:
              - name: test-cm
                mountPath: /tests
          volumes:
            - name: test-cm
              configMap:
                name: erc20-test-configmap
                items:
                  - key: eth_erc20.py
                    path: eth_erc20.py
                  - key: SecurityToken.abi
                    path: SecurityToken.abi
                  - key: SecurityToken.bin
                    path: SecurityToken.bin
                  - key: testerc20.sh
                    path: testerc20.sh
                  - key: ethrpc.cert
                    path: ethrpc.cert
          restartPolicy: OnFailure
kind: List
metadata: {}
